export enum TypeKeys {
  POSTS_LOADING = 'POSTS_LOADING',
  POSTS_SUCCESS = 'POSTS_SUCCESS',
  POSTS_FAIL = 'POSTS_FAIL',
  ADD_POST = 'ADD_POST',
  EDIT_POST = 'EDIT_POST',
  REMOVE_POST = 'REMOVE_POST',
  COMMENTS_LOADING = 'COMMENTS_LOADING',
  COMMENTS_SUCCESS = 'COMMENTS_SUCCESS',
  COMMENTS_FAIL = 'COMMENTS_FAIL',
}
